# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastpcdtest_balanced_ <- function(M) {
    .Call('fastpcdtest_fastpcdtest_balanced_', PACKAGE = 'fastpcdtest', M)
}

fastpcdtest_unbalanced_ <- function(M, min_common) {
    .Call('fastpcdtest_fastpcdtest_unbalanced_', PACKAGE = 'fastpcdtest', M, min_common)
}

